{"uuid": "d3dc1e2a-6486-45a6-a70c-71260b1d13e3", "children": ["6285f864-43f5-4cb1-b487-48d44a3781cb"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "RuntimeError: All attempts to create Remote driver failed. Last exception: TypeError(\"WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'\")\n", "trace": "  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\projects\\mobile-demo\\conftest.py\", line 116, in driver\n    drv = _create_ios_driver(\n        device_name=os.getenv(\"IOS_DEVICE_NAME\", \"iPhone 15 Pro\"),\n        platform_version=os.getenv(\"IOS_PLATFORM_VERSION\", \"17.0\"),\n        app_id=os.getenv(\"IOS_APP_ID\")\n    )\n  File \"C:\\projects\\mobile-demo\\conftest.py\", line 95, in _create_ios_driver\n    return _try_create_remote(\"https://hub.browserstack.com/wd/hub\", caps)\n  File \"C:\\projects\\mobile-demo\\conftest.py\", line 82, in _try_create_remote\n    raise RuntimeError(\"All attempts to create Remote driver failed. Last exception: {}\".format(repr(last_exc)))\n"}, "start": 1757913323594, "stop": 1757913323611}], "start": 1757913323594, "stop": 1757913323766}