{"name": "test_valid_login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed with valid credentials\nassert False\n +  where False = is_logged_in()\n +    where is_logged_in = <pages.login_page.LoginPage object at 0x00000205A2613750>.is_logged_in", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"645628684a691d0b36ad234db9cb21b0100833c3\")>\n\n    @pytest.mark.smoke\n    def test_valid_login(driver):\n        lp = LoginPage(driver)\n        # SauceLabs sample app valid creds\n        lp.login(\"standard_user\", \"secret_sauce\")\n>       assert lp.is_logged_in(), \"Login failed with valid credentials\"\nE       AssertionError: Login failed with valid credentials\nE       assert False\nE        +  where False = is_logged_in()\nE        +    where is_logged_in = <pages.login_page.LoginPage object at 0x00000205A2613750>.is_logged_in\n\ntests\\test_login.py:10: AssertionError"}, "attachments": [{"name": "screenshot-android", "source": "6bf99994-adfc-40d9-a673-ac599f8a135b-attachment.png", "type": "image/png"}], "start": 1757857613628, "stop": 1757857618444, "uuid": "911e2095-4730-4f70-b2a5-95f2ae601381", "historyId": "ab68c09e23714aa68c720c2ca07c0ecf", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "12140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}