{"name": "test_valid_login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed with valid credentials\nassert False\n +  where False = is_logged_in()\n +    where is_logged_in = <pages.login_page.LoginPage object at 0x00000192B1273750>.is_logged_in", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"5ad714638d390e93fda49818b38e7432a4620880\")>\n\n    @pytest.mark.smoke\n    def test_valid_login(driver):\n        lp = LoginPage(driver)\n        # SauceLabs sample app valid creds\n        lp.login(\"standard_user\", \"secret_sauce\")\n>       assert lp.is_logged_in(), \"Login failed with valid credentials\"\nE       AssertionError: Login failed with valid credentials\nE       assert False\nE        +  where False = is_logged_in()\nE        +    where is_logged_in = <pages.login_page.LoginPage object at 0x00000192B1273750>.is_logged_in\n\ntests\\test_login.py:10: AssertionError"}, "attachments": [{"name": "screenshot-android", "source": "2dbc2069-15fb-4b3c-8b8c-8df194323e9b-attachment.png", "type": "image/png"}], "start": 1757857723812, "stop": 1757857728453, "uuid": "0d4ef78f-641a-4f80-ad6d-b3a360728cf8", "historyId": "ab68c09e23714aa68c720c2ca07c0ecf", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "5096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}