{"name": "test_sort_by_price", "status": "broken", "statusDetails": {"message": "RuntimeError: Username field not found (tried multiple locators)", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"055163a101570badbfe166a4acf3a1a0bd26cea5\")>\n\n    @pytest.mark.smoke\n    def test_sort_by_price(driver):\n        lp = LoginPage(driver)\n>       lp.login(\"standard_user\", \"secret_sauce\")\n\ntests\\test_sort.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:69: in login\n    self.enter_username(username)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x00000214321E60F0>, username = 'standard_user'\n\n    def enter_username(self, username):\n        loc = self._find_first(self._locator_username_candidates(), timeout=6)\n        if not loc:\n>           raise RuntimeError(\"Username field not found (tried multiple locators)\")\nE           RuntimeError: Username field not found (tried multiple locators)\n\npages\\login_page.py:49: RuntimeError"}, "attachments": [{"name": "screenshot-android", "source": "f40f8b74-8068-4f2c-8092-fc79157c09cf-attachment.png", "type": "image/png"}], "start": 1757853399741, "stop": 1757853431507, "uuid": "8a63b34d-8c66-488e-9a7f-04b476b94405", "historyId": "5129378306a2b17ebcf1e696ee3b7d48", "testCaseId": "5129378306a2b17ebcf1e696ee3b7d48", "fullName": "tests.test_sort#test_sort_by_price", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_sort"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "1268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_sort"}], "titlePath": ["tests", "test_sort.py"]}