{"name": "test_add_to_cart", "status": "broken", "statusDetails": {"message": "RuntimeError: Username field not found (tried multiple locators)", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"b18aea18305da9dc57aa19d08a9a89434fb7e74d\")>\n\n    @pytest.mark.smoke\n    def test_add_to_cart(driver):\n        lp = LoginPage(driver)\n>       lp.login(\"standard_user\", \"secret_sauce\")\n\ntests\\test_cart.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:69: in login\n    self.enter_username(username)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x0000021432278EC0>, username = 'standard_user'\n\n    def enter_username(self, username):\n        loc = self._find_first(self._locator_username_candidates(), timeout=6)\n        if not loc:\n>           raise RuntimeError(\"Username field not found (tried multiple locators)\")\nE           RuntimeError: Username field not found (tried multiple locators)\n\npages\\login_page.py:49: RuntimeError"}, "attachments": [{"name": "screenshot-android", "source": "b91514ef-9375-4586-8c29-4a5bc37465ad-attachment.png", "type": "image/png"}], "start": 1757853141848, "stop": 1757853173562, "uuid": "4cc74c5a-2d4b-46d3-bf94-5757a1463055", "historyId": "f53930c71791373588d426a984620050", "testCaseId": "f53930c71791373588d426a984620050", "fullName": "tests.test_cart#test_add_to_cart", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cart"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "1268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cart"}], "titlePath": ["tests", "test_cart.py"]}