{"name": "test_valid_login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed with valid credentials\nassert False\n +  where False = is_logged_in()\n +    where is_logged_in = <pages.login_page.LoginPage object at 0x00000229CB0A0EC0>.is_logged_in", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"4811aad7c9fbe588d973e572c938efb59103012a\")>\n\n    @pytest.mark.smoke\n    def test_valid_login(driver):\n        lp = LoginPage(driver)\n        # SauceLabs sample app valid creds\n        lp.login(\"standard_user\", \"secret_sauce\")\n>       assert lp.is_logged_in(), \"Login failed with valid credentials\"\nE       AssertionError: Login failed with valid credentials\nE       assert False\nE        +  where False = is_logged_in()\nE        +    where is_logged_in = <pages.login_page.LoginPage object at 0x00000229CB0A0EC0>.is_logged_in\n\ntests\\test_login.py:9: AssertionError"}, "attachments": [{"name": "screenshot-android", "source": "0f882df1-7efc-4c03-a5f4-70d899dd01c5-attachment.png", "type": "image/png"}], "start": 1757837153215, "stop": 1757837178051, "uuid": "108440d4-76e8-4eb2-a092-94dc21e2e5a3", "historyId": "ab68c09e23714aa68c720c2ca07c0ecf", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "10892-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}